### ISSUE TITLE
Could you share the dataset splits used in the paper?

### ISSUE THREAD

**Issue by hongluzhou** [shudan/PCTADW#2]
Thanks for sharing the code! I wonder, could you kindly share with me the dataset splits used in the paper? It would be a lot easier for me to conduct a fair comparison. Thanks in advance!!

**Comment by shudan** [comment]
Hi Honglu, I added the notebook for logistic regression test under the same repo. It may contain the code you need. https://github.com/shudan/PCTADW/blob/master/regression_test.ipynb

**Comment by hongluzhou** [comment]
> Hi Honglu, I added the notebook for logistic regression test under the same repo. It may contain the code you need. https://github.com/shudan/PCTADW/blob/master/regression_test.ipynb

Thanks for sharing (and your reply)!!
